### ISSUE TITLE
Missing ch.cern.cmms.eamtools Dependency

### ISSUE THREAD

**Issue by thecrowbar** [cern-eam/eam-light-backend#1]
Trying to build this project and unable to find the eamtools artifact referenced in the pom.xml file. Will this code be released as well?

Thank you,
James Crow

**Comment by LukaszPater** [comment]
Hi James,

we will get rid of it in v1.0, which will be released in 1-2 days. We use eamtools to implement cross-cutting concerns specific to CERN. If you don't feel like waiting for the v1.0 release I can gladly instruct on how to proceed. 

Cheers
Lukasz

**Comment by thecrowbar** [comment]
Thank you for the information. I will wait until the new release.
