### ISSUE TITLE
how to install EAM light?

### ISSUE THREAD

**Issue by Miladkhaghanirad** [cern-eam/eam-light-backend#10]
Hello guys,
i am working in BASF in Ludwigshafen and we have Eam-Infor installed in our Server went to install your program(EAM-Light) but i have problem with it. i run backend in port 8081 from docker and i add user in it.so i can login to Wildfly from port 9090. Then i build my frontend docker from Docker File and run it in port 8080.I faces login page but when i write my data on it and click on login button it will Freeze don't know what should i do or how should i fix it.
thanks in advance
best regards
Milad Khaghanirad

**Comment by jpizarrom** [comment]
@Miladkhaghanirad did you created the EULLAY Grid?
