### ISSUE TITLE
Elaborate steps on building light-backend

### ISSUE THREAD

**Issue by lokeshv23** [cern-eam/eam-light-backend#66]
Hello,

I have tried building the light-backend repo with all the ear / war / jar files compiled and ready but still unable to get the APIs running.

Can you please add more elaborate details on building the cern-eam/eam-light-backend. Thank you.

Regards
Lokesh

**Comment by LukaszPater** [comment]
Hello Lokesh,

I would need more information. Could you explain what steps are you executing and what is not working? Of course once we have understood the problem we will update the documentation. 

Best regards,
Lukasz

**Comment by lokeshv23** [comment]
Hello  Lukasz,

Below are the steps I am performing -

1. Download master repo from "https://github.com/cern-eam/eam-light-backend"
2. Run maven install - I then see the required ear, jar and war generated
getting created
3. Verified the creation of
"eam-light-backendear/target/eam-light-backend.ear"
4. Create a docker image
5. Started the docker image with command - docker run -p 8080:8080 -p
9090:9090 --env EAMLIGHT_INFOR_WS_URL=<Valid_WS_URL> <image_name with tag>
6. Verified that Wildlfy server is running in Docker
7. But I am unable to verify APIs, have tried following URLs but no luck -
http://localhost:9090/apis, http://localhost:9090/apis/rest,
http://localhost:8080/rest, http://localhost:8080/apis/rest

Regards
Lokesh

**Comment by lokeshv23** [comment]
Hello Lukasz,

You can ignore my issue and close it.

It seems the build and deployment was working fine but the URLs I was
trying were wrong. I am now able to access the backend APIs - example - "
http://localhost:8080/rest/parts/<partnumber> - works now.

Thank you for your support.

Regards
Lokesh
